version: 0.2

#env:
#  variables:
#  parameter-store:
            
phases:
  install:
    commands:
      - gem install asciidoctor
      - gem install asciidoctor-pdf --pre
  build:
    commands:
      - ls
      - pwd
      - asciidoctor-pdf -d book --safe -D dist src/index.adoc
#  post_build:
#    commands:
#artifacts:
#  files:
#    - location
#    - location
#  discard-paths: yes
#  base-directory: location
#cache:
#  paths:
#    - path
#    - path